# Generic security enhancements. Use https://securityheaders.io to test
# and recommend further improvements.

# Hide Nginx version in error messages and reponse headers.
server_tokens off;

# Don't allow pages to be rendered in an iframe on external domains.
add_header X-Frame-Options "SAMEORIGIN" always;

# MIME sniffing prevention
add_header X-Content-Type-Options "nosniff" always;

# Disable XSS Auditor. Deprecated in modern browsers and can introduce
# vulnerabilities. CSP is the proper replacement for XSS protection.
add_header X-Xss-Protection "0" always;

# Whitelist sources which are allowed to load assets (JS, CSS, etc). The following will block
# only none HTTPS assets, but check out https://scotthelme.co.uk/content-security-policy-an-introduction/
# for an in-depth guide on creating a more restrictive policy.
add_header Content-Security-Policy "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';" always;

# Control how much referrer information is sent with requests.
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Restrict access to browser features not needed by most WordPress sites.
add_header Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()" always;